# Настройки ConfigMap
springDatasource:
  url: "jdbc:postgresql://51.250.0.205:5432/CoffeeAndTea"
  username: "sasha"

# Настройки Secret
postgresPassword: ""

# Настройки Deployment
replicaCount: 2
image:
  repository: midzaru2011/coffee-and-tea-app
  tag: "2.1.2"
  pullPolicy: IfNotPresent

# Настройки Service
service:
  type: LoadBalancer
  port: 8082
  targetPort: 8082
  sessionAffinity: ClientIP
